name: JSON Schema Validation

on:
  push:
    paths:
      - 'examples/*.json'
      - 'schemas/*.json'
    branches:
      - main
  pull_request:
    paths:
      - 'examples/*.json'
      - 'schemas/*.json'
  workflow_dispatch:


jobs:
  check-json-schema:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-check-jsonschema
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install check-jsonschema
      run: pip install check-jsonschema

    - name: Validate JSON documents
      run: |
        for filename in examples/*_*.json; do
          base=$(basename -- "$filename")
          name="${base%.*}"
          IFS="_" read -ra parts <<< "$name"
          objectType="${parts[-1]}"
          check-jsonschema --schemafile "schemas/${objectType}.schema.json" "$filename" 
        done
        